name: Trigger auto deployment for goofy-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/goofy-app-AutoDeployTrigger-ae635b8b-ce6c-44b8-a953-d7ea50e985e5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.GOOFYAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GOOFYAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GOOFYAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.GOOFYAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GOOFYAPP_REGISTRY_PASSWORD }}
          containerAppName: goofy-app
          resourceGroup: my-projects
          imageToBuild: maheeen453/goofy-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


